### ISSUE TITLE
Imports default to using backslash rather than forward slash on Windows.

### ISSUE THREAD

**Issue by kvoth3** [capaj/vscode-exports-autocomplete#19]
operating system: win10

steps to reproduce: 
Type a known component that resides in another file. When found, press tab to import.

![image](https://i.gyazo.com/613a7c86b57e06d8b28d0daedc5cce46.gif)

**Comment by capaj** [comment]
oh I totally forgot about that! Will be releasing a fix in the next 4 hours!

**Comment by capaj** [comment]
published as 0.3.4

**Comment by kvoth3** [comment]
Awesome, that was fast!

**Comment by capaj** [comment]
@kvoth3 I just hope it works :D I haven't really tested it as I am on my ubuntu laptop now :grin:

**Comment by kvoth3** [comment]
Don't worry I just updated and it works fine!
